apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-discogs-api.fullname" . }}
  labels:
    {{- include "open-discogs-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "open-discogs-api.selectorLabels" . | nindent 4 }}
