# netty
server:
  shutdown: graceful
  port: 8080
  http2:
    enabled: true
  forward-headers-strategy: framework
# spring
spring:
  application:
    name: open-discogs-api
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    banner-mode: off
# observability
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  server:
    port: 8081
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
    tags:
      application: open-discogs-api
  endpoint:
    health:
      probes:
        enabled: on
logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
    io.dsub.sweatboys: TRACE
#    io.r2dbc.postgresql.QUERY: TRACE # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
# swagger
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls-primary-name: Public
    display-request-duration: true
    defaultModelsExpandDepth: -1
    use-root-path: true
    urls:
      - display-name: Open Discogs API
        name: Open Discogs API
        url: ${API_SERVER_URL:http://localhost:8080}/v3/api-docs
  enable-native-support: true
  default-flat-param-object: true
  api-docs:
    groups:
      enabled: true
