# netty
server:
  shutdown: graceful
  http2:
    enabled: true

# spring
spring:
  application:
    name: open-discogs-api
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

# observability
management:
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui
  server:
    port: 9090
logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
# swagger
springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
  show-spring-cloud-functions: false
  show-actuator: false
  use-management-port: true
  enable-native-support: true